### ISSUE TITLE
Update the sample application to use resource scanning

### ISSUE THREAD

**Issue by btiernay** [dsyer/spring-boot-jersey#2]
Most of the time people will choose scanning over explicitly adding resources as it is easier to maintain. It might be better to illustrate this in the sample with `package(Endpoint.class.getPackage().getName())` instead of `register(Endpoint.class)`

**Comment by jasenkoh** [comment]
And what do you think about registering all resources within a package like: 

<code>
public JerseyInitialization(){
        this.packages("com.package.name");
    }
</code>

I have implemented it into my Spring Boot demo app

https://github.com/jasenkoh/REST-spring-boot-jersey

**Comment by btiernay** [comment]
@jasenkoh I think using a class literal is preferred since it is more refactoring friendly (e.g. it will survive across package renames).

**Comment by dsyer** [comment]
Since these features moved to Spring Boot, it's probably better to catch up there.
