### ISSUE TITLE
Jersey Servlet doesn't play nice with Spring Dispatcher Servlet

### ISSUE THREAD

**Issue by alin-simionoiuDE** [dsyer/spring-boot-jersey#4]
if there's a solution to this problem, i can't seem to find it. I have a spring boot app where i need to use both spring MVC request mappings (@RequestMapping) and jersey/jaxrs mapping with @Path and all that.

apparently jersey servlet takes over and none of the @RequestMapping are getting calling anymore. I did try to use @ApplicationPath in my ResourceConfig and i get this exception which i didn't got before

```
java.lang.IllegalStateException: The resource configuration is not modifiable in this context.
    at org.glassfish.jersey.server.ResourceConfig$ImmutableState.addProperties(ResourceConfig.java:244)
    at org.glassfish.jersey.server.ResourceConfig$ImmutableState.addProperties(ResourceConfig.java:221)
    at org.glassfish.jersey.server.ResourceConfig.addProperties(ResourceConfig.java:399)
```

which according to what i can find on the inter webs can mean a whole lot of things..grrr.

is there any way to make these two work together? (yes, i do need them to work together).

**Comment by havasuski** [comment]
More than likely you'll need to initialize a servlet for Spring MVC, and a second for Jersey. Set one with a higher priority than the other. In addition if you're configuring the Jersey servlet in your WebApplicationInitilizer (to specify servlet order, and for which spring context to pull from), then you should not use @ApplicationPath(...) on the resource config. @ApplicationPath in addition to the servlet config will essentially load two different servlets, the one via @ApplicationPath will not be aware of your spring context and therefore any autowiring to beans in your spring context will be null.
